spring:
  application:
    name: mywedding-app

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mywedding-esprit-fad8.a.aivencloud.com:28558/mywedding?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_mzVkZ33kAdXakaT5cXJ

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
      properties:
        hibernate.format_sql: true

  server:
    port: 8080
