package com.mywedding.weddingPlanner.plannerBaseEntities;

import com.mywedding.weddingPlanner.weddingHall.entity.WeddingHall;
import jakarta.persistence.*;
import lombok.*;

@Data
@Entity
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Table (name = "service_images")
public class ServiceImages {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;
    private String type;
    @Lob
    @Column(name = "imagedata",length = 1000, columnDefinition = "LONGBLOB")
    private byte[] imageData;

    @ToString.Exclude
    @ManyToOne
    @JoinColumn(name = "wedding_hall_id")
    private WeddingHall weddingHall;


    // Constructors, getters, and setters (generated by Lombok)
}
