package com.mywedding.weddingPlanner.plannerBaseEntities;

import com.mywedding.identity.entities.User;
import com.mywedding.weddingPlanner.weddingHall.entity.WeddingHall;
import jakarta.persistence.*;
import lombok.Data;
import lombok.ToString;

@Data
@Entity
@Table(name = "user_review")
public class UserReview {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private double rating;
    private String comment;
    private String time;

    @ManyToOne
    private User user;

    @ToString.Exclude
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "wedding_hall_id")
    private WeddingHall weddingHall;
    // Getters and setters (generated by Lombok)
}