package com.mywedding.weddingEvents.entities;

import com.mywedding.identity.entities.User;
import jakarta.persistence.*;
import lombok.Data;
import org.antlr.v4.runtime.misc.NotNull;

@Data
@Entity
@Table(name = "events")
public class WeddingEvent {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;

    private String location;

    private double price;

    private String description;

    @ManyToOne
    @NotNull
    private User createdBy; // User who created the event

    // Getters and setters (generated by Lombok)
}
