package com.mywedding.weddingHall.entities;

import jakarta.persistence.*;
import lombok.Data;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

@Data
@Entity
@Table (name = "wedding_hall_images")
public class WeddingHallImage {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String imagePath;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "wedding_hall_id")
    @OnDelete(action = OnDeleteAction.CASCADE)
    private WeddingHall weddingHall;

    // Constructors, getters, and setters (generated by Lombok)
}
