package com.mywedding.weddingHall.entities;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

@Data
@Entity
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Table (name = "wedding_hall_images")
public class WeddingHallImage {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;
    private String type;
    @Lob
    @Column(name = "imagedata",length = 1000, columnDefinition = "LONGBLOB")
    private byte[] imageData;

    @ToString.Exclude
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "wedding_hall_id")
    private WeddingHall weddingHall;

    // Constructors, getters, and setters (generated by Lombok)
}
